package Vistas;

import java.awt.Image;
import java.net.URL;
import javax.swing.ImageIcon;
import java.util.Random;
import javax.swing.JOptionPane;

public class NewJFrame extends javax.swing.JFrame {

    private int numeroSecreto;
    private int intentos = 0;
    private int ayudas = 0;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NewJFrame.class.getName());

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        Random random = new Random();

        numeroSecreto = random.nextInt(900) + 100;

        txtDigito1.setText(String.valueOf(numeroSecreto).substring(0, 1));
        txtDigito2.setText(String.valueOf(numeroSecreto).substring(1, 2));
        txtDigito3.setText(String.valueOf(numeroSecreto).substring(2, 3));

        txtDigito1.setEchoChar('$');
        txtDigito2.setEchoChar('$');
        txtDigito3.setEchoChar('$');

        txtDigito1.setEditable(false);
        txtDigito2.setEditable(false);
        txtDigito3.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        pnlCodigo = new javax.swing.JPanel();
        txtDigito3 = new javax.swing.JPasswordField();
        txtDigito1 = new javax.swing.JPasswordField();
        txtDigito2 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnRevelar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtIntento = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lblImagen = new javax.swing.JLabel();
        lblPista = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        txtDigito3.setBackground(new java.awt.Color(102, 255, 102));
        txtDigito3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        txtDigito3.setForeground(new java.awt.Color(0, 0, 0));
        txtDigito3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDigito3.setText("$");
        txtDigito3.setToolTipText("$");
        txtDigito3.setEchoChar('$');
        txtDigito3.addActionListener(this::txtDigito3ActionPerformed);

        txtDigito1.setBackground(new java.awt.Color(204, 153, 255));
        txtDigito1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        txtDigito1.setForeground(new java.awt.Color(0, 0, 0));
        txtDigito1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDigito1.setText(".");
        txtDigito1.setToolTipText("");
        txtDigito1.setEchoChar('$');

        txtDigito2.setBackground(new java.awt.Color(255, 255, 153));
        txtDigito2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        txtDigito2.setForeground(new java.awt.Color(0, 0, 0));
        txtDigito2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDigito2.setText("$");
        txtDigito2.setToolTipText("$");
        txtDigito2.setEchoChar('$');

        javax.swing.GroupLayout pnlCodigoLayout = new javax.swing.GroupLayout(pnlCodigo);
        pnlCodigo.setLayout(pnlCodigoLayout);
        pnlCodigoLayout.setHorizontalGroup(
            pnlCodigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCodigoLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(txtDigito1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(txtDigito2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(txtDigito3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        pnlCodigoLayout.setVerticalGroup(
            pnlCodigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCodigoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pnlCodigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDigito2)
                    .addComponent(txtDigito1)
                    .addComponent(txtDigito3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Por favor ingresa exactamente 3 numeros");

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 2, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 51));
        jLabel2.setText("Codigo Secreto");

        btnRevelar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRevelar.setText("Revelar");
        btnRevelar.addActionListener(this::btnRevelarActionPerformed);

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));

        txtIntento.setBackground(new java.awt.Color(255, 204, 204));
        txtIntento.setForeground(new java.awt.Color(0, 0, 0));
        txtIntento.addActionListener(this::txtIntentoActionPerformed);
        txtIntento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIntentoKeyTyped(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 204, 204));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setText("Ingrese 3 numeros + enter");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                    .addComponent(txtIntento))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIntento, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lblPista.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPista.setForeground(new java.awt.Color(255, 255, 51));

        desktopPane.setLayer(pnlCodigo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(btnRevelar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(lblImagen, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(lblPista, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopPaneLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(desktopPaneLayout.createSequentialGroup()
                        .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(desktopPaneLayout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(desktopPaneLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(lblPista, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(132, 132, 132))
                    .addGroup(desktopPaneLayout.createSequentialGroup()
                        .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(desktopPaneLayout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61)
                                .addComponent(btnRevelar, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopPaneLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(lblPista, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, desktopPaneLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, desktopPaneLayout.createSequentialGroup()
                        .addComponent(btnRevelar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))
                    .addGroup(desktopPaneLayout.createSequentialGroup()
                        .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRevelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRevelarActionPerformed
        if (ayudas >= 2) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "No hay más revelaciones"
            );
            return;
        }
        if (ayudas == 0) {
            txtDigito1.setEchoChar((char) 0);
        } else if (ayudas == 1) {
            txtDigito2.setEchoChar((char) 0);
        }
        ayudas++;
    }//GEN-LAST:event_btnRevelarActionPerformed

    private void txtDigito3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDigito3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDigito3ActionPerformed

    private void txtIntentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIntentoKeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            evt.consume();
            return;
        }

        String input = txtIntento.getText() + c;

        if (input.length() > 3) {
            evt.consume();
        }
    }//GEN-LAST:event_txtIntentoKeyTyped

    private void txtIntentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIntentoActionPerformed
        String input = txtIntento.getText();
        if (input.length() != 3 || !input.matches("\\d+")) {

            JOptionPane.showMessageDialog(
                    this,
                    "Ingresá exactamente 3 números"
            );
            return;
        }
        intentos++;
        String secreto = String.valueOf(numeroSecreto);
        if (input.charAt(0) == secreto.charAt(0)) {
            txtDigito1.setEchoChar((char) 0);
        }
        if (input.charAt(1) == secreto.charAt(1)) {
            txtDigito2.setEchoChar((char) 0);
        }
        if (input.charAt(2) == secreto.charAt(2)) {
            txtDigito3.setEchoChar((char) 0);
        }
        int intento = Integer.parseInt(input);
        if (intento < numeroSecreto) {
            lblPista.setText("Más alto");
        } else if (intento > numeroSecreto) {
            lblPista.setText("Más bajo");
        } else {
            lblPista.setText("¡Correcto!");
            try {
                URL url = new URL(
                        "https://images.vexels.com/media/users/3/202189/isolated/lists/4f3a5cb84297726d74d69dce22676f83-trofeo-numero-1-plano.png"
                );
                ImageIcon icon = new ImageIcon(url);
                Image imagen = icon.getImage().getScaledInstance(
                        120,
                        120,
                        Image.SCALE_SMOOTH
                );
                lblImagen.setIcon(new ImageIcon(imagen));
            } catch (Exception e) {
                System.out.println("Error al cargar la imagen del trofeo");
            }
            JOptionPane.showMessageDialog(
                    this,
                    "¡Ganaste!\nCantidad de intentos: " + intentos
            );
        }
        txtIntento.setText("");
    }//GEN-LAST:event_txtIntentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new NewJFrame().setVisible(true));
    }
//hola
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRevelar;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblPista;
    private javax.swing.JPanel pnlCodigo;
    private javax.swing.JPasswordField txtDigito1;
    private javax.swing.JPasswordField txtDigito2;
    private javax.swing.JPasswordField txtDigito3;
    private javax.swing.JTextField txtIntento;
    // End of variables declaration//GEN-END:variables
}
